version: '2'
services:
  mariadb:
    image: bitnami/mariadb:10.6
    environment:
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3307:3306'
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    image: bitnami/moodle:4.3
    environment:
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_NAME=moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      #   - '.:/bitnami/moodle/local/translate'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
